# Generated by Django 2.0.7 on 2018-10-26 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20181026_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepost',
            old_name='user_like',
            new_name='users_like',
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 26, 7, 35, 24, 71954, tzinfo=utc)),
        ),
    ]
