# Generated by Django 2.0.7 on 2018-10-28 03:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20181028_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='article',
        ),
        migrations.AddField(
            model_name='collection',
            name='article_collect',
            field=models.ManyToManyField(blank=True, related_name='collection_article', to='article.ArticlePost'),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 3, 48, 1, 647161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='collection',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector', to=settings.AUTH_USER_MODEL),
        ),
    ]
