# Generated by Django 2.0.7 on 2018-10-28 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20181028_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 28, 4, 6, 57, 197111, tzinfo=utc)),
        ),
    ]
