# Generated by Django 2.0.7 on 2018-10-29 04:05

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0011_auto_20181028_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='article_collect',
            field=models.ManyToManyField(blank=True, related_name='collection_article', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 4, 5, 4, 694025, tzinfo=utc)),
        ),
    ]
