# Generated by Django 2.1.7 on 2019-03-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('body', models.TextField(verbose_name='文章内容')),
                ('is_secret', models.IntegerField(choices=[(0, '不是隐私'), (1, '隐私')], default=0, verbose_name='是否为隐私文章')),
                ('liker', models.IntegerField(default=0, verbose_name='喜欢文章人数')),
                ('unliker', models.IntegerField(default=0, verbose_name='不喜欢文章人数')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'tb_article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('body', models.TextField(verbose_name='文章内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '草稿',
                'verbose_name_plural': '草稿',
                'db_table': 'tb_article_draft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '文章标签',
                'verbose_name_plural': '文章标签',
                'db_table': 'tb_article_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollationSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_title', models.CharField(max_length=30, verbose_name='一级标题')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '整合集',
                'verbose_name_plural': '整合集',
                'db_table': 'tb_collation_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CollationSetBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_title', models.CharField(max_length=30, verbose_name='二级标题')),
                ('body', models.TextField(verbose_name='内容')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '整合集文章内容',
                'verbose_name_plural': '整合集文章内容',
                'db_table': 'tb_collation_set_body',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, verbose_name='标签名')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tb_tag',
                'managed': False,
            },
        ),
    ]
